version = 0.1
[default.deploy.parameters]
stack_name = "real-time-feedback-collection"
resolve_s3 = true
s3_prefix = "real-time-feedback-collection"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
