AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Real time feedback collection 

  Sample SAM Template for Real time feedback collection

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  FeedbackApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  SubmitFeedbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: submitfeedbackfunction
      Handler: dist/submitfeed/app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Submit:
          Type: Api
          Properties:
            Path: /submit
            Method: POST
            RestApiId: !Ref FeedbackApi
      Environment:
        Variables:
          TABLE_NAME: !Ref FeedbackTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable

  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "submit-feedback"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for dev for real time feedback"
    Value: !Sub "https://${FeedbackApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
