AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Real time feedback collection 

  Sample SAM Template for Real time feedback collection

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  FeedbackApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  SubmitFeedbackFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: nodejs16.x
    Properties:
      FunctionName: submitfeedbackfunction
      Handler: dist/submitfeed/app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Submit:
          Type: Api
          Properties:
            Path: /submit
            Method: POST
            RestApiId: !Ref FeedbackApi
      Environment:
        Variables:
          TABLE_NAME: !Ref FeedbackTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable

  NotifyAdminsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: nodejs16.x
    Properties:
      FunctionName: notifyadminsfunction
      Handler: dist/notifyadmins/app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FeedbackTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
      Environment:
        Variables:
          TABLE_NAME: !Ref FeedbackTable
          TOPIC_ARN: !Ref FeedbackNotifications
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable
        - DynamoDBStreamReadPolicy:
            StreamName: "*"
            TableName: !Ref FeedbackTable
        - SNSPublishMessagePolicy:
            TopicName: "real-time-feedback-collection-FeedbackNotifications-6fMF8vFhWqG5"

  EmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: macandy99@gmail.com

  ProcessFeedbackFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: nodejs16.x
    Properties:
      FunctionName: processfeedbackfunction
      Handler: dist/processfeed/app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        PollMessage:
          Type: SQS
          Properties:
            Queue: !GetAtt FeedbackQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          TABLE_NAME: !Ref FeedbackTable
          TOPIC_ARN: !Ref FeedbackNotifications
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeedbackTable
        - SQSPollerPolicy:
            QueueName: !Ref FeedbackQueue
        - SESCrudPolicy:
            IdentityName: "*"

  FeedbackNotifications:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: FeedbackNotificationsTopic
      # TopicName: FeedbackNotificationsTopicName

  FeedbackQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FeedbackQueue
      MessageRetentionPeriod: 120
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FeedbackDLQQueue.Arn
        maxReceiveCount: 2

  FeedbackDLQQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: FeedbackQueueDLQ

  SNSToSQSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref FeedbackNotifications
      Endpoint: !GetAtt FeedbackQueue.Arn

  FeedbackAdminEmailNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref FeedbackNotifications
      Endpoint: hi@macandersonuche.dev

  SNSToSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - "sqs:SendMessage"
              - "sqs:SendMessageBatch"
            Resource: !GetAtt FeedbackQueue.Arn
      Queues:
        - !Ref FeedbackQueue

  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "submit-feedback"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for dev for real time feedback"
    Value: !Sub "https://${FeedbackApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
